server:
    address: localhost:48290

    # user - who owns the service
    user: shortly

    # server logging configuration
    access_log: logs/access.log
    error_log: logs/error.log

# redis configuration
redis:
  address: localhost:6379
  retries: 10

log:
  outputPaths: 
    - logs/app.log
  level: DEBUG
  encoding: "json"
  development: true
      